### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by ardimasp** [TheNightJourney/NotSoBulletSpeedBulletTrain#1]
<img width="816" alt="image" src="https://user-images.githubusercontent.com/5621601/212783178-8a01654b-52d2-4f8b-9a8b-2bdf3fabcd6e.png">

**Comment by TheNightJourney** [comment]
Compilation error is fixed, occuring due to definition of functions after the main function.
Conflicting types also fixed, occured as well due to no specific delcaration, and calling of the function before its definition.
